name: Integration Test
on:
  push:
    branches:
      - master
      - release-5.0
      - release-4.0
      - release-3.0
  pull_request:
    branches:
      - master
      - release-5.0
      - release-4.0
      - release-3.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: validation
        run: |
          git clone git@github.com:pingcap/tidb.git
          cd tidb
          rm go.sum
          GO111MODULE=on go mod edit -replace github.com/pingcap/parser=github.com/${{github.repository}}@${{github.sha}}
          go mod tidy
          # use only 1 thread to minimize memory usage (we've only got 2 CPU + 4 GB on Circle CI).
          make gotest P=1
